services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  db:
    image: postgres:latest
    container_name: postgres-db
    env_file: 
      - ./ChatDay/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  celery:
    build: .
    command: celery -A ChatDay worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A ChatDay beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80" 
    depends_on:
      - web 

volumes:
  postgres-data:  