# Generated by Django 5.1.2 on 2024-11-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(default='기본주제', max_length=200),
            preserve_default=False,
        ),
    ]
